package ru.hse.server;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import ru.hse.IAccountDataSource;
import ru.hse.IAuthorizationSource;
import ru.hse.OperationResponse;

import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.Properties;

public class ServerStorage implements IAccountDataSource, IAuthorizationSource {
    private HikariDataSource source;
    private final String filename;

    public ServerStorage(String filename) {
        this.filename = filename;
        setupDatabase();
        initDatabase();
    }

    private void setupDatabase() {
        String pass = "", username = "SA";
        try (InputStream input =
                     ServerStorage.class.getClassLoader().getResourceAsStream("db.properties")) {
            Properties prop = new Properties();

            if (input == null) {
                System.out.println("Sorry, unable to find config.properties");
                return;
            }
            prop.load(input);
            pass = prop.getProperty("db.password");
            username = prop.getProperty("db.user");

        } catch (IOException ex) {
            ex.printStackTrace();
        }

        HikariConfig config = new HikariConfig();
        // Файловая БД: все данные в одном файле mydb.data
        config.setJdbcUrl("jdbc:hsqldb:file:./" + filename + ";shutdown=true");
        config.setUsername(username);
        config.setPassword(pass); // wontfix
        config.setMaximumPoolSize(10);
        config.setConnectionTimeout(30000);
        config.setLeakDetectionThreshold(10000);
        source = new HikariDataSource(config);
    }

    private void initDatabase() {
        String createSessionsTable =
                """
                        CREATE TABLE IF NOT EXISTS sessions (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            login VARCHAR(50) UNIQUE NOT NULL
                        )
                        """;
        String createAccountsTable =
                """
                            CREATE TABLE IF NOT EXISTS accounts(
                                login VARCHAR(50) UNIQUE NOT NULL,
                                password_hash VARCHAR(60) NOT NULL,
                                amount FLOAT
                            )
                        """;
        String insertAccounts =
                """
                        INSERT INTO accounts (login, password_hash, amount) VALUES
                        ('user', 'user', 10.99)
                        """;

        String checkAccounts = "SELECT COUNT(*) FROM accounts";

        try (Connection conn = source.getConnection();
             Statement stmt = conn.createStatement()) {

            stmt.executeUpdate(createAccountsTable);
            stmt.executeUpdate(createSessionsTable);

            // Добавляем тестовые данные в items, если таблица пуста
            ResultSet rs = stmt.executeQuery(checkAccounts);
            rs.next();
            if (rs.getInt(1) == 0) {
                stmt.executeUpdate(insertAccounts);
                System.out.println("Тестовые данные добавлены.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException("Не удалось инициализировать БД", e);
        }
    }

    IAccountChangeVerifier verifier = null;

    public void setChangeVerifier(IAccountChangeVerifier accountSecurity) {
        this.verifier = accountSecurity;
    }

    @Override
    public OperationResponse withdraw(String login, long session, double balance) {
        if (verifier != null) {
            int ret = verifier.approveChange(login, -1 * balance);
            if (ret != OperationResponse.SUCCEED) {
                if (ret == OperationResponse.NO_MONEY)
                    return new OperationResponse(ret, getBalance(login, session));
                return new OperationResponse(ret, null);
            }
        }
        String sql = "UPDATE accounts SET amount = amount - ? WHERE login = ?";
        try (Connection conn = source.getConnection()) {
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setDouble(1, balance);
                stmt.setString(2, login);
                int rs = stmt.executeUpdate();
                if (rs > 0) {
                    return getBalance(login, session);
                }
            }
            return new OperationResponse(OperationResponse.NO_USER_INCORRECT_PASSWORD, null);
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
    }

    @Override
    public OperationResponse deposit(String login, long session, double balance) {
        if (verifier != null) {
            int ret = verifier.approveChange(login, balance);
            if (ret != OperationResponse.SUCCEED) {
                if (ret == OperationResponse.NO_MONEY)
                    return new OperationResponse(ret, getBalance(login, session));
                return new OperationResponse(ret, null);
            }
        }
        String sql = "UPDATE accounts SET amount = amount + ? WHERE login = ?";
        try (Connection conn = source.getConnection()) {
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setDouble(1, balance);
                stmt.setString(2, login);
                int rs = stmt.executeUpdate();
                if (rs > 0) {
                    return getBalance(login, session);
                }
            }
            return new OperationResponse(OperationResponse.NO_USER_INCORRECT_PASSWORD, null);
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
    }

    @Override
    public OperationResponse getBalance(String login, long session) {
        String sql = "SELECT amount FROM accounts WHERE login = ?";
        try (Connection conn = source.getConnection()) {
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, login);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    return new OperationResponse(OperationResponse.SUCCEED, rs.getDouble(1));
                }
            }
            return new OperationResponse(OperationResponse.NO_USER_INCORRECT_PASSWORD, null);
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
    }

    @Override
    public OperationResponse register(String login, String password) {
        if (login == null || password == null)
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, null);
        String sql = "SELECT login, password_hash FROM accounts WHERE login = ?";
        try (Connection conn = source.getConnection()) {
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, login);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    return new OperationResponse(OperationResponse.ALREADY_LOGGED, null);
                }
            }
            String sql2 = "INSERT INTO accounts(login, password_hash, amount) VALUES (?, ?, 0)";
            try (PreparedStatement stmt = conn.prepareStatement(sql2)) {
                stmt.setString(1, login);
                stmt.setString(2, password);
                int cnt = stmt.executeUpdate();
                if (cnt > 0) {
                    return initSession(conn, login);
                }
                return new OperationResponse(OperationResponse.ALREADY_LOGGED, null);
            } catch (SQLException e) {
                return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
            }
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
    }

    @Override
    public OperationResponse login(String login, String password) {
        if (login == null || password == null)
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, null);
        String sql = "SELECT login, password_hash FROM accounts WHERE login = ?";
        try (Connection conn = source.getConnection()) {
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, login);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    String storedHash = rs.getString("password_hash");
                    if (password.equals(storedHash)) return initSession(conn, login);
                }
                return new OperationResponse(OperationResponse.NO_USER_INCORRECT_PASSWORD, null);
            }
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
    }

    private OperationResponse initSession(Connection conn, String login) {
        String sql = "INSERT INTO sessions (login) VALUES (?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, login);
            int cnt = stmt.executeUpdate();
            if (cnt == 0) {
                return new OperationResponse(OperationResponse.ALREADY_LOGGED, null);
            }
        } catch (SQLIntegrityConstraintViolationException notFirst) {
            return new OperationResponse(OperationResponse.ALREADY_LOGGED, notFirst.getMessage());
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
        sql = "SELECT id, login FROM sessions WHERE login = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, login);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                String sessionId = rs.getString("id");
                return new OperationResponse(OperationResponse.SUCCEED, sessionId);
            }
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
        return new OperationResponse(OperationResponse.UNDEFINED_ERROR, null);
    }

    private OperationResponse stopSession(Connection conn, Long sessId) {
        String sql = "DELETE FROM sessions WHERE id = ?;";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setLong(1, sessId);
            int cnt = stmt.executeUpdate();
            if (cnt == 0) {
                return new OperationResponse(OperationResponse.NOT_LOGGED, null);
            }
            return new OperationResponse(OperationResponse.SUCCEED, null);
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
    }

    @Override
    public OperationResponse logout(String login, Long activeSession) {
        if (login == null || activeSession == null)
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, null);
        try (Connection conn = source.getConnection()) {
            return stopSession(conn, activeSession);
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
    }

    protected OperationResponse testSession(String login, Long session) {
        String sql = "SELECT id FROM sessions WHERE id = ? AND login = ?;";
        try (Connection conn = source.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setLong(1, session);
            stmt.setString(2, login);
            int cnt = stmt.executeUpdate();
            if (cnt == 0) {
                return new OperationResponse(OperationResponse.NOT_LOGGED, null);
            }
            return new OperationResponse(OperationResponse.SUCCEED, null);
        } catch (SQLException e) {
            return new OperationResponse(OperationResponse.UNDEFINED_ERROR, e.getMessage());
        }
    }
}
